# Site settings
title:
email:
author:
description:
url:

# Build settings
permalink: :title/
sass:
  sass_dir: css

# Social icons
show_social_icons: true
twitter_username: tweetsinwelsh

# Collections 
collections:
  blog:
    output: true

plugins:
- jekyll-paginate


paginate: 8
paginate_path: "/page:num/"

