#-------------------------------
# General Site Settings

title: Tweets in Welsh
subtitle: Learning to read Welsh, one tweet at a time...
email: robertdpowell@gmail.com
author: Rob Powell

summary: >
  This is an experiment to see how quickly I can improve my Welsh reading skills and vocabulary through daily translation of a small piece of everyday Welsh. A new tweet will be posted each day.


sources:
- {link: 'https://twitter.com/gigsgcg'}
- {link: 'https://twitter.com/cyngorcaerdydd'}
- {link: 'https://twitter.com/Museum_Cardiff'}


#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'www.google.com'}
- {icon: 'facebook', link: 'www.google.com'}
- {icon: 'linkedin', link: 'www.google.com'}
- {icon: 'youtube', link: 'www.google.com'}
- {icon: 'instagram', link: 'www.google.com'}

# can be 'twitter' / 'facebook' / 'github' / 'pinterest' / 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'soundcloud'
