#-------------------------------
# General Site Settings


blurb: Learning to read Welsh, one Tweet at a time...
email: tweetsinwelsh@gmail.com
author: Rob Powell
bannerimage: /img/learnwelsh.png
bannerimagealt: Learn Welsh





  