#-------------------------------
# General Site Settings


blurb: Prosiect Dysgu Cymraeg
email: tweetsinwelsh@gmail.com
author: Rob Powell
bannerimage: /img/learnwelsh.png
bannerimagealt: Learn Welsh





  