#-------------------------------
# General Site Settings

title: Dysgu Cymraeg
blurb: Robert Powell -  Sylfaen Foundation (A2)
email: tweetsinwelsh@gmail.com
author: Rob Powell
bannerimage: /img/learnwelsh.png
bannerimagealt: Learn Welsh





  