#-------------------------------
# General Site Settings

title: devops etc
subtitle: a blog by Rob Powell
email: robertdpowell@gmail.com
author: Rob Powell

blurb:

  "Software delivery can be complicated.  I enjoy simplifying the complex,  learning about techniques to improve software delivery performance and sharing what I learn."

  DevOps Etc. is written by Rob Powell.

  Rob is DevOps Adoption Manager at a global financial services company, a role which sees him help the organisation to adopt Agile and Devops practices in order to continuously
  improve their software delivery performance. Prior to this, Rob spent over a decade working for a number of organisations in a range of  software delivery roles - Business Analyst, Project Manager, Scrummaster, Product Owner.
  

















#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'www.google.com'}
- {icon: 'facebook', link: 'www.google.com'}
- {icon: 'linkedin', link: 'www.google.com'}
- {icon: 'youtube', link: 'www.google.com'}
- {icon: 'instagram', link: 'www.google.com'}

# can be 'twitter' / 'facebook' / 'github' / 'pinterest' / 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'soundcloud'
