#-------------------------------
# General Site Settings


blurb: Dysgu Cymraeg, un trydar ar y tro...
email: tweetsinwelsh@gmail.com
author: Rob Powell
bannerimage: /img/learnwelsh.png
bannerimagealt: Learn Welsh





  