#-------------------------------
# General Site Settings

title: devops etc
subtitle: a blog by Rob Powell
email: robertdpowell@gmail.com

blurb: >
  Rob specializes in making other people [look good]
  Most of the things he makes are [digital interfaces](http://atradius.com {:target="_blank"},
  but he also puts effort into crafting [next-level beats](http://soundcloud.com/travis-neilson){:target="_blank"}
  and [YouTube videos](http://youtube.com/user/devtipsfordesigners){:target="_blank"} about making change happen.





#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'www.google.com'}
- {icon: 'facebook', link: 'www.google.com'}
- {icon: 'linkedin', link: 'www.google.com'}
- {icon: 'youtube', link: 'www.google.com'}
- {icon: 'instagram', link: 'www.google.com'}

# can be 'twitter' / 'facebook' / 'github' / 'pinterest' / 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'soundcloud'
